### ISSUE TITLE
using node 0.11.14

### ISSUE THREAD

**Issue by debonair** [mattrobenolt/node-mock-udp#1]
I am failing to get this to work with node version 0.11.14

**Comment by mattrobenolt** [comment]
@debonair What's the issue you're seeing?

**Comment by mattrobenolt** [comment]
I've just told Travis to run tests against 0.11, and it's fine: https://travis-ci.org/mattrobenolt/node-mock-udp/builds/47801119

**Comment by debonair** [comment]
I am trying to mock udp calls to statsd using https://github.com/msiebuhr/node-statsd-client/ from my application.

I ended up using https://github.com/msiebuhr/node-statsd-client/blob/master/test/FakeServer.js because I kept getting " Error: Scope was not used!"

**Comment by mattrobenolt** [comment]
I'm closing this because this just seems like user error to me unless proven otherwise. That error is explicitly raised when the scope has not been executed. It's not a bug in this library.
